INSERT INTO concert (concert_name, concert_date) VALUES ('LKR', '2024-10-30');
INSERT INTO concert (concert_name, concert_date) VALUES ('LEEKR', '2024-10-31');

-- INSERT INTO seat (seat_Number, reservation_Id, is_Available) VALUES (1, 1, true);
-- INSERT INTO seat (seat_Number, reservation_Id, is_Available) VALUES (2, 1, true);
-- INSERT INTO seat (seat_Number, reservation_Id, is_Available) VALUES (3, 1, true);
-- INSERT INTO seat (seat_Number, reservation_Id, is_Available) VALUES (4, 1, false);
-- INSERT INTO seat (seat_Number, reservation_Id, is_Available) VALUES (5, 1, false);
-- INSERT INTO seat (seat_Number, reservation_Id, is_Available) VALUES (6, 1, true);
-- INSERT INTO seat (seat_Number, reservation_Id, is_Available) VALUES (7, 1, true);
-- INSERT INTO seat (seat_Number, reservation_Id, is_Available) VALUES (8, 1, true);
-- INSERT INTO seat (seat_Number, reservation_Id, is_Available) VALUES (9, 1, false);
-- INSERT INTO seat (seat_Number, reservation_Id, is_Available) VALUES (10, 1, false);


-- INSERT INTO RESERVE (IS_TEMPORARY, RESERVATION_DATE, CONCERT_ID, EXPORATION_TIME, RESERVATION_ID, SEAT_ID, USER_ID) VALUES (TRUE, '2024-10-27', 1, '2024-10-27', 1, 1, 1)

INSERT INTO user_info (pay, user_name) VALUES (15000, 'user2');
INSERT INTO user_info (pay, user_name) VALUES (5000, 'user1');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user3');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user4');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user5');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user6');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user7');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user8');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user9');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user10');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user11');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user12');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user13');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user14');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user15');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user16');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user17');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user18');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user19');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user20');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user21');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user22');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user23');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user24');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user25');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user26');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user27');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user28');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user29');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user30');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user31');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user32');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user33');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user34');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user35');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user36');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user37');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user38');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user39');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user40');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user41');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user42');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user43');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user44');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user45');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user46');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user47');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user48');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user49');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user50');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user51');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user52');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user53');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user54');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user55');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user56');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user57');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user58');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user59');
INSERT INTO user_info (pay, user_name) VALUES (15000, 'user60');

